### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by Helpme0822** [gjacobs314/HQTrivia#11]
Is there any possibility to use that on windows?

**Comment by gjacobs314** [comment]
no, its for mac OS only.

**Comment by Helpme0822** [comment]
okay and btw the website is not working

**Comment by gjacobs314** [comment]
the site does work actually. only works for US games and only works when i’m home running the client. i’m not there for all games.

**Comment by yapal** [comment]
Can we run on virtual machine " snow leopard version"
