### ISSUE TITLE
Website Displaying Show not on - During show

### ISSUE THREAD

**Issue by bacondude3** [gjacobs314/HQTrivia#14]
As of Friday 3/23/18 @ 9 the website did not broadcast the answers - does this possibly have something to do with my data connection, I have speeds of around 1-2mbps

**Comment by Allmight3** [comment]
The website only works to answer questions when the developer has it set up on his computer. If you wish to not rely on it then follow the instructions in the git to install it locally.

**Comment by bacondude3** [comment]
Got it Thanks!
