### ISSUE TITLE
Which version swift is required

### ISSUE THREAD

**Issue by yapal** [gjacobs314/HQTrivia#15]
I don't know more about Mac. Sorry if I'm wrong. 
1)Can we run this virtual machine of snow leopard?
2)what is minimum version of xcode required to run your program?
3) what is minimum version of swift required?

Plz reply to all questions...

**Comment by gjacobs314** [comment]
It uses the latest Xcode version and latest Swift version (I don't know if you can run on Snow Leopard, never tried a virtual machine). Just download the latest version of Xcode from the App Store and then open it there and you'll be good.

**Comment by Allmight3** [comment]
I'm on windows and use android and have it working. It does work with High Sierra in a virtual machine. There's a lot of setup though so it will likely be too much for most people! Just do some googling and you can figure it all out though, that's what I did.

**Comment by yapal** [comment]
Allmight3:
What is configuration of ur pc?
1) Windows version
2) processor etc
  

I have Windows 7 ( 32 bit) core 2 duo. 2 Gb ram. Can I run high Sierra on virtualbox

**Comment by Allmight3** [comment]
Yes. https://www.howtogeek.com/289594/how-to-install-macos-sierra-in-virtualbox-on-windows-10/

Just follow that guide. It says it's for windows 10 but it'd be the same for WIndows 7. Good luck.

**Comment by gjacobs314** [comment]
^
