### ISSUE TITLE
what do i need to do when i run the program and get this error

### ISSUE THREAD

**Issue by joerialcapone** [gjacobs314/HQTrivia#18]
what do i need to do when i run the program and get this error

<img width="798" alt="schermafbeelding 2018-03-26 om 15 34 08" src="https://user-images.githubusercontent.com/37780440/37909436-3411c984-310b-11e8-9f5f-539a55bf3517.png">

**Comment by SyncedCyberSoul** [comment]
I think what that means is you need to do a pod install.

**Comment by SyncedCyberSoul** [comment]
this has been answered by gordon already, I guess https://github.com/gjacobs314/HQTrivia/issues/5
