### ISSUE TITLE
Y'all a prankster mang XD

### ISSUE THREAD

**Issue by SyncedCyberSoul** [gjacobs314/HQTrivia#20]
I loved it tonight the little comments and changes were funny as hell. shame i didn't get the sneakers. how about that, 4 pairs in the world.

<img width="1257" alt="screen shot 2018-03-26 at 10 05 48 pm" src="https://user-images.githubusercontent.com/8508334/37942844-18e9467c-3143-11e8-87ed-f80c0695ed0a.png">
<img width="1261" alt="screen shot 2018-03-26 at 10 10 42 pm" src="https://user-images.githubusercontent.com/8508334/37942845-18f56290-3143-11e8-9947-1f171ae49d79.png">

hehe. Mind helping me out though, so I can get this running locally? I think I've entered everything correctly, but I do not get questions/answers on the application. Just sits there like a dead fish. Like my cat.

**Comment by gjacobs314** [comment]
There are a two places you need to put the API key and CSE ID and make sure you have the right userID in the url and a valid Bearer token.

**Comment by SyncedCyberSoul** [comment]
Yup. instead of having people have to manually put it in, why not make a UI dropdown or side panel like  Daniel smith's original code. I really like this UI, It's very clean and simple. I've been attempting to use his because I never can get the websocket to work correctly, though.

**Comment by gjacobs314** [comment]
Also say goodbye to website, HQ emailed me telling me to take it down. I won't be running it anymore (or at least it won't show answers). And no I am not going to make a UI for that.
