### ISSUE TITLE
Entering Bearer token, user id, Google API key, and Google CSE ID

### ISSUE THREAD

**Issue by jakelibs22** [gjacobs314/HQTrivia#25]
I appreciate you sharing this script. I am fairly new to coding and am having trouble figuring out where to plug in all the info. Would it be in lines 31, 50, 57 at the end of the link, and 83 of ViewController.swift and lines 13, 14, 57, and 79 in the parenthesis of SiteEncoding.swift? I would greatly appreciate it if you can let me know if I missed anywhere or added any spots to enter the info that shouldn't be. Thanks in advance!

**Comment by gjacobs314** [comment]
Everything is right except you don't need 57 or 79. All others you are correct.

**Comment by jakelibs22** [comment]
Thanks for the quick reply. Do I keep the parenthesis or quotation marks around them or take them out?

**Comment by rusd1123** [comment]
What do you mean by "end of the link" (lines 31, 50 & 57?)

Also, just to confirm, in the _ViewController.swift_, we do not need to adjust lines 19 and 20 (Bearer Token and User ID?)

Thanks for your help!

**Comment by gjacobs314** [comment]
By end of link I mean for the user ID you put it at the end of the link on the line I say... the end of the link would be XXXX but you want those XXXX to be ur user ID.

**Comment by rusd1123** [comment]
Gotcha, so lines 31, 50 and 57 of which file?

**Comment by gjacobs314** [comment]
Please read the readme before asking me things...

Fill in info in lines 31, 50, 57 at the end of the link, and 83 of
ViewController.swift and lines 13, and 14 in SiteEncoding.swift

**Comment by spaz926** [comment]
#38 could solve this confusion for average users with no coding background. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
