### ISSUE TITLE
No such module 

### ISSUE THREAD

**Issue by moevanp** [gjacobs314/HQTrivia#27]
Hi ,

Im trying to run this project and i installed the pods from cocoapods
but I keep getting "No such module" for import KeychainSwift and Alamofire

please assist

**Comment by gjacobs314** [comment]
Pod install

**Comment by moevanp** [comment]
Thanks for the prompt reply i did pod install in the same directory as the project but i still get the error even tried update pod

**Comment by moevanp** [comment]
which version of xcode and swift should be used?
