### ISSUE TITLE
Can you please make it work for loco, brain baazi and iq live trivia apps.

### ISSUE THREAD

**Issue by PoonamChohdhary1991** [gjacobs314/HQTrivia#28]
iQ live -https://play.google.com/store/apps/details?id=live.trivia.iq
Loco- 
https://play.google.com/store/apps/details?id=com.showtimeapp
Brain baazi- 
https://play.google.com/store/apps/details?id=com.brainbaazi

**Comment by gjacobs314** [comment]
No, do it yourself.

**Comment by PoonamChohdhary1991** [comment]
Atleast can you help me do it?
