### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by Dojoro** [gjacobs314/HQTrivia#3]
Hi,

I have a question about the way the websocket works. I know that when a message is received, it is checked if it is a question then it parses the answers and sets the labels as their string value then solves (chat messages come through with the socket too, so this is why you have to check the type). 

How is a message from a client sent back through the socket? When I chat or answer a question I don't see any data sent back though (even when viewing through a MITM proxy). Any idea? thanks.

**Comment by gjacobs314** [comment]
i don’t think you’ll be able to make it answer for you if that’s what you’re trying to do. i haven’t tried it but a friend told me it’s encyprted/hashed so it’s not really that easy to send your result without using the HQ app.
