### ISSUE TITLE
No such module 'KeychainSwift'

### ISSUE THREAD

**Issue by Tesla-MX2** [gjacobs314/HQTrivia#30]
Hi i'm having issues with running the bot. When I run it it says No such module 'KeychainSwift' in the SiteEncoding.Swift . When I run the bot i open the HackQ.xcodeproj is this correct or do i need to use the worspace one? 
![image](https://user-images.githubusercontent.com/38264286/38583269-7a5afa1a-3ce0-11e8-9d5d-b91bc5462e9c.png)
 When I run the workplace file it opens but when the game is live it doesnt do anything.

**Comment by gjacobs314** [comment]
You have to fill in all your info, read the readme for specific lines. You should be running the HackQ.xcworkspace file only
