### ISSUE TITLE
I am receiving 2 WebSocket Issues (deprecated string method) 

### ISSUE THREAD

**Issue by donron2325** [gjacobs314/HQTrivia#40]
Swift Compiler Warning:

'substring(to:)' is deprecated: Please use String slicing subscript with a 'partial range upto' operator.

'substring(from:)' is deprecated: Please use String slicing subscript with a 'partial range from' operator.

else {
                    key = ""
                    if let r = line.range(of: ":") {
                        key = trim(line.substring(to: r.lowerBound))
                        value = trim(line.substring(from: r.upperBound))
                    }

**Comment by gjacobs314** [comment]
Try re-downloading the whole project and DON'T run a pod install because I think you might have updated the pods and that messed stuff up.
