### ISSUE TITLE
WebSocket.swift

### ISSUE THREAD

**Issue by Daednoise** [gjacobs314/HQTrivia#5]
When I try to run the project I receive this error on WebSocket.swift:
**Argument labels '(truncatingIfNeeded:)' do not match any available overloads**
for this line:
` f.statusCode = UInt16(truncatingIfNeeded: code)`

**Comment by gjacobs314** [comment]
Is there a fix to it? It's a pod, so it isn't something I made. Try doing a fix all and it should work fine.
